spring:
  # 数据库连接
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog_db?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # mybatis-plus 配置
mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
  #type-aliases-package: com.dgut.blog.entity
  configuration:
    # 开启驼峰
    map-underscore-to-camel-case: true